name: CI | Test Worker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11 & install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: |
          python -m pip install --upgrade pip
          pip install -r builder/requirements.txt

      - name: Test Worker
        run: |
          python src/whatever.py --test_input='{"input": {"number": 2}}'

      - name: Test Worker Failure
        run: |
          python src/whatever.py --test_input='{"input": {"number": "this will fail"}}'
          exit_code=$?
          if [ $exit_code -eq 0 ]; then
            echo "Test failed: zero exit code returned."
            exit 1
          else
            echo "Test passed: non-zero exit code returned."
          fi
